apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart
spec:
  selector:
    matchLabels:
      app: shopping-cart
  replicas: 1 
  template: 
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
      - name: shopping-cart
        image: nareshbabu1991/shopping-cart:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-cart
spec:
  type: LoadBalancer
  selector:
    app: shopping-cart
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
